language: node_js
dist: trusty
node_js:
- 8.1.0
cache:
  directories:
  - node_modules
notifications:
  email: false
  slack:
    secure: itJvmzZBxRDxc/D0X5uX4DZ/DahoJt1JBblS2ob1SVbOW++3hPj+Nl1nlUaoFEkVn+wfKMpxWyLjAwmU3HkdwjY75CFWKHDdS67StiaLv7tA7ybVYGZiihnPSVLgP0HLpBHax2HqNqRRvLPpFLZc5PrrAVwwbCf1bSHMxmqSSXWpM24F0g1eSLpOT6X3JvckmaD/U0TGUwvKbD3mZ54eDXSNjSnAYZ7y2524crGXO7KVVUuoWqthdJppK9FGXMrx/F/qzkzv9i4w73PQkcXk8gHlbgiyA2e7NBMKJM3T5iBS0hx5zoZtG468Tqo/9QSpKWiq4qNae/5zfThp1ERF9mUPhXQQPQQo4PW+SS3vJNBXVbW7uYZNbESeiXsl94Ojmo+2dAA3sQOTZj/tRxtjIf+v9oOOoLQl5BkolBjnZfU449J/zz0uZRXJG43kqTJG4+mLdEwJ+fKIQZhLNtMJm58uAydn+Lfp5q4cw9VZ8WzDl5hULd0XwnT7FdRyzfLHacA4h1oip+VI6/zK9289S0Hmtb62LrMyQTAxOj+AFQRyLieUt1pKt1bYp1hjNELuiWKSB7SaPTEsrM3SkGkIDe9cl2rx2fEpM1KrwCMAoKOpWOxrVtQPkRtNUxo/45DwsaUxlqJtUwk0zhIZeVJLmN+Hsn6HF6pfCJz5+FcV4uM=
